// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const aPIUsageStats = `-- name: APIUsageStats :one
SELECT
    COALESCE(SUM(requests_this_month), 0)::bigint AS total_requests_this_month,
    COUNT(*) FILTER (WHERE revoked_at IS NULL)::bigint AS active_keys
FROM api_keys
`

type APIUsageStatsRow struct {
	TotalRequestsThisMonth int64 `json:"total_requests_this_month"`
	ActiveKeys             int64 `json:"active_keys"`
}

func (q *Queries) APIUsageStats(ctx context.Context) (APIUsageStatsRow, error) {
	row := q.db.QueryRow(ctx, aPIUsageStats)
	var i APIUsageStatsRow
	err := row.Scan(&i.TotalRequestsThisMonth, &i.ActiveKeys)
	return i, err
}

const activateUserAdmin = `-- name: ActivateUserAdmin :exec
UPDATE users SET status = 'active', updated_at = NOW() WHERE id = $1
`

func (q *Queries) ActivateUserAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, activateUserAdmin, id)
	return err
}

const changeUserWorkspaceRoleAdmin = `-- name: ChangeUserWorkspaceRoleAdmin :exec
UPDATE workspace_members SET role = $3 WHERE user_id = $1 AND workspace_id = $2
`

type ChangeUserWorkspaceRoleAdminParams struct {
	UserID      uuid.UUID `json:"user_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Role        string    `json:"role"`
}

func (q *Queries) ChangeUserWorkspaceRoleAdmin(ctx context.Context, arg ChangeUserWorkspaceRoleAdminParams) error {
	_, err := q.db.Exec(ctx, changeUserWorkspaceRoleAdmin, arg.UserID, arg.WorkspaceID, arg.Role)
	return err
}

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(*) FROM users WHERE deleted_at IS NULL AND status = 'active'
`

func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM admin_audit_logs
`

func (q *Queries) CountAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUploads = `-- name: CountUploads :one
SELECT COUNT(*) FROM analyses WHERE deleted_at IS NULL
`

func (q *Queries) CountUploads(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUploads)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUploadsAdmin = `-- name: CountUploadsAdmin :one
SELECT COUNT(*) FROM analyses
WHERE ($1::bool OR deleted_at IS NULL)
  AND ($2::text = '' OR keyword ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR status = $3)
`

type CountUploadsAdminParams struct {
	IncludeDeleted bool   `json:"include_deleted"`
	Search         string `json:"search"`
	StatusFilter   string `json:"status_filter"`
}

func (q *Queries) CountUploadsAdmin(ctx context.Context, arg CountUploadsAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUploadsAdmin, arg.IncludeDeleted, arg.Search, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUploadsThisMonth = `-- name: CountUploadsThisMonth :one
SELECT COUNT(*) FROM analyses WHERE deleted_at IS NULL AND created_at >= date_trunc('month', NOW())
`

func (q *Queries) CountUploadsThisMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUploadsThisMonth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUploadsToday = `-- name: CountUploadsToday :one
SELECT COUNT(*) FROM analyses WHERE deleted_at IS NULL AND created_at >= CURRENT_DATE
`

func (q *Queries) CountUploadsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUploadsToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserUploads = `-- name: CountUserUploads :one
SELECT COUNT(*) FROM analyses WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountUserUploads(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserUploads, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one

SELECT COUNT(*) FROM users WHERE deleted_at IS NULL
`

// Dashboard -------------------------------------------------------------
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersAdmin = `-- name: CountUsersAdmin :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL
  AND ($1::text = '' OR email ILIKE '%' || $1 || '%' OR full_name ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR status = $2)
`

type CountUsersAdminParams struct {
	Search       string `json:"search"`
	StatusFilter string `json:"status_filter"`
}

func (q *Queries) CountUsersAdmin(ctx context.Context, arg CountUsersAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersAdmin, arg.Search, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admin_users (email, password_hash, full_name, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, full_name, role, is_active, last_login_at, created_at, updated_at
`

type CreateAdminParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	FullName     string `json:"full_name"`
	Role         string `json:"role"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
	)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAdminRefreshToken = `-- name: CreateAdminRefreshToken :one
INSERT INTO admin_refresh_tokens (admin_id, token_hash, device_info, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, admin_id, token_hash, device_info, is_revoked, expires_at, created_at
`

type CreateAdminRefreshTokenParams struct {
	AdminID    uuid.UUID          `json:"admin_id"`
	TokenHash  string             `json:"token_hash"`
	DeviceInfo pgtype.Text        `json:"device_info"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAdminRefreshToken(ctx context.Context, arg CreateAdminRefreshTokenParams) (AdminRefreshToken, error) {
	row := q.db.QueryRow(ctx, createAdminRefreshToken,
		arg.AdminID,
		arg.TokenHash,
		arg.DeviceInfo,
		arg.ExpiresAt,
	)
	var i AdminRefreshToken
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.DeviceInfo,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO admin_audit_logs (admin_id, action, target_type, target_id, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, admin_id, action, target_type, target_id, metadata, created_at
`

type CreateAuditLogParams struct {
	AdminID    uuid.UUID `json:"admin_id"`
	Action     string    `json:"action"`
	TargetType string    `json:"target_type"`
	TargetID   string    `json:"target_id"`
	Metadata   []byte    `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AdminAuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.AdminID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	var i AdminAuditLog
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const dailySignupTrend = `-- name: DailySignupTrend :many

SELECT date_trunc('day', created_at)::date AS bucket, COUNT(*) AS count
FROM users
WHERE deleted_at IS NULL AND created_at >= NOW() - interval '30 days'
GROUP BY bucket
ORDER BY bucket
`

type DailySignupTrendRow struct {
	Bucket pgtype.Date `json:"bucket"`
	Count  int64       `json:"count"`
}

// Analytics -----------------------------------------------------------------
func (q *Queries) DailySignupTrend(ctx context.Context) ([]DailySignupTrendRow, error) {
	rows, err := q.db.Query(ctx, dailySignupTrend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailySignupTrendRow{}
	for rows.Next() {
		var i DailySignupTrendRow
		if err := rows.Scan(&i.Bucket, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dailyUploadTrend = `-- name: DailyUploadTrend :many
SELECT date_trunc('day', created_at)::date AS bucket, COUNT(*) AS count
FROM analyses
WHERE deleted_at IS NULL AND created_at >= NOW() - interval '30 days'
GROUP BY bucket
ORDER BY bucket
`

type DailyUploadTrendRow struct {
	Bucket pgtype.Date `json:"bucket"`
	Count  int64       `json:"count"`
}

func (q *Queries) DailyUploadTrend(ctx context.Context) ([]DailyUploadTrendRow, error) {
	rows, err := q.db.Query(ctx, dailyUploadTrend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyUploadTrendRow{}
	for rows.Next() {
		var i DailyUploadTrendRow
		if err := rows.Scan(&i.Bucket, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fileTypeBreakdown = `-- name: FileTypeBreakdown :many
SELECT lower(substring(thumbnail_s3_key from '\.([a-zA-Z0-9]+)$')) AS extension, COUNT(*) AS count
FROM analyses
WHERE deleted_at IS NULL
GROUP BY extension
ORDER BY count DESC
`

type FileTypeBreakdownRow struct {
	Extension string `json:"extension"`
	Count     int64  `json:"count"`
}

// The upload pipeline currently always writes .jpg regardless of the
// original content type (see usecase/analysis.Create), so this will read as
// entirely "jpg" today — grouping by the real stored extension keeps this
// query correct if that ever changes, rather than hardcoding "jpg".
func (q *Queries) FileTypeBreakdown(ctx context.Context) ([]FileTypeBreakdownRow, error) {
	rows, err := q.db.Query(ctx, fileTypeBreakdown)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FileTypeBreakdownRow{}
	for rows.Next() {
		var i FileTypeBreakdownRow
		if err := rows.Scan(&i.Extension, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, full_name, role, is_active, last_login_at, created_at, updated_at FROM admin_users WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, password_hash, full_name, role, is_active, last_login_at, created_at, updated_at FROM admin_users WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminRefreshToken = `-- name: GetAdminRefreshToken :one
SELECT id, admin_id, token_hash, device_info, is_revoked, expires_at, created_at FROM admin_refresh_tokens WHERE token_hash = $1 AND is_revoked = FALSE AND expires_at > NOW()
`

func (q *Queries) GetAdminRefreshToken(ctx context.Context, tokenHash string) (AdminRefreshToken, error) {
	row := q.db.QueryRow(ctx, getAdminRefreshToken, tokenHash)
	var i AdminRefreshToken
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.DeviceInfo,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAppSettings = `-- name: GetAppSettings :one

SELECT id, max_upload_size_bytes, allowed_extensions, feature_flags, storage_provider, email_provider, email_from_address, updated_at FROM app_settings WHERE id = 1
`

// Settings --------------------------------------------------------------
func (q *Queries) GetAppSettings(ctx context.Context) (AppSetting, error) {
	row := q.db.QueryRow(ctx, getAppSettings)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.MaxUploadSizeBytes,
		&i.AllowedExtensions,
		&i.FeatureFlags,
		&i.StorageProvider,
		&i.EmailProvider,
		&i.EmailFromAddress,
		&i.UpdatedAt,
	)
	return i, err
}

const getUploadAdmin = `-- name: GetUploadAdmin :one
SELECT id, workspace_id, project_id, user_id, keyword, keyword_normalized, thumbnail_s3_key, status, score, visibility_score, contrast_score, attention_score, mobile_score, branding_score, curiosity_score, cv_results, competitor_avg, suggestions, competitor_count, rank_in_competitors, error_message, retry_count, created_at, updated_at, deleted_at, relevance_score, relevance_reasoning, actual_ctr, published_at, file_size_bytes FROM analyses WHERE id = $1
`

func (q *Queries) GetUploadAdmin(ctx context.Context, id uuid.UUID) (Analysis, error) {
	row := q.db.QueryRow(ctx, getUploadAdmin, id)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.UserID,
		&i.Keyword,
		&i.KeywordNormalized,
		&i.ThumbnailS3Key,
		&i.Status,
		&i.Score,
		&i.VisibilityScore,
		&i.ContrastScore,
		&i.AttentionScore,
		&i.MobileScore,
		&i.BrandingScore,
		&i.CuriosityScore,
		&i.CvResults,
		&i.CompetitorAvg,
		&i.Suggestions,
		&i.CompetitorCount,
		&i.RankInCompetitors,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RelevanceScore,
		&i.RelevanceReasoning,
		&i.ActualCtr,
		&i.PublishedAt,
		&i.FileSizeBytes,
	)
	return i, err
}

const getUserDetailAdmin = `-- name: GetUserDetailAdmin :one
SELECT
    u.id, u.email, u.password_hash, u.full_name, u.avatar_url, u.google_id, u.email_verified, u.stripe_customer_id, u.created_at, u.updated_at, u.deleted_at, u.status,
    COALESCE(ws.plan, '') AS plan,
    ws.id AS workspace_id,
    COALESCE(agg.analyses_count, 0)::bigint AS analyses_count,
    COALESCE(agg.storage_used, 0)::bigint AS storage_used
FROM users u
LEFT JOIN LATERAL (
    SELECT w.id, w.plan FROM workspace_members wm
    JOIN workspaces w ON w.id = wm.workspace_id AND w.deleted_at IS NULL
    WHERE wm.user_id = u.id
    ORDER BY wm.joined_at ASC
    LIMIT 1
) ws ON true
LEFT JOIN LATERAL (
    SELECT COUNT(*) AS analyses_count, COALESCE(SUM(file_size_bytes), 0) AS storage_used
    FROM analyses
    WHERE analyses.user_id = u.id AND analyses.deleted_at IS NULL
) agg ON true
WHERE u.id = $1
`

type GetUserDetailAdminRow struct {
	ID               uuid.UUID          `json:"id"`
	Email            string             `json:"email"`
	PasswordHash     pgtype.Text        `json:"password_hash"`
	FullName         string             `json:"full_name"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	GoogleID         pgtype.Text        `json:"google_id"`
	EmailVerified    bool               `json:"email_verified"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	Status           string             `json:"status"`
	Plan             string             `json:"plan"`
	WorkspaceID      uuid.UUID          `json:"workspace_id"`
	AnalysesCount    int64              `json:"analyses_count"`
	StorageUsed      int64              `json:"storage_used"`
}

func (q *Queries) GetUserDetailAdmin(ctx context.Context, id uuid.UUID) (GetUserDetailAdminRow, error) {
	row := q.db.QueryRow(ctx, getUserDetailAdmin, id)
	var i GetUserDetailAdminRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.EmailVerified,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Status,
		&i.Plan,
		&i.WorkspaceID,
		&i.AnalysesCount,
		&i.StorageUsed,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, admin_id, action, target_type, target_id, metadata, created_at FROM admin_audit_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAuditLog{}
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentUploads = `-- name: ListRecentUploads :many
SELECT id, workspace_id, project_id, user_id, keyword, keyword_normalized, thumbnail_s3_key, status, score, visibility_score, contrast_score, attention_score, mobile_score, branding_score, curiosity_score, cv_results, competitor_avg, suggestions, competitor_count, rank_in_competitors, error_message, retry_count, created_at, updated_at, deleted_at, relevance_score, relevance_reasoning, actual_ctr, published_at, file_size_bytes FROM analyses WHERE deleted_at IS NULL ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListRecentUploads(ctx context.Context, limit int32) ([]Analysis, error) {
	rows, err := q.db.Query(ctx, listRecentUploads, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Analysis{}
	for rows.Next() {
		var i Analysis
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.UserID,
			&i.Keyword,
			&i.KeywordNormalized,
			&i.ThumbnailS3Key,
			&i.Status,
			&i.Score,
			&i.VisibilityScore,
			&i.ContrastScore,
			&i.AttentionScore,
			&i.MobileScore,
			&i.BrandingScore,
			&i.CuriosityScore,
			&i.CvResults,
			&i.CompetitorAvg,
			&i.Suggestions,
			&i.CompetitorCount,
			&i.RankInCompetitors,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RelevanceScore,
			&i.RelevanceReasoning,
			&i.ActualCtr,
			&i.PublishedAt,
			&i.FileSizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentUsers = `-- name: ListRecentUsers :many
SELECT id, email, password_hash, full_name, avatar_url, google_id, email_verified, stripe_customer_id, created_at, updated_at, deleted_at, status FROM users WHERE deleted_at IS NULL ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListRecentUsers(ctx context.Context, limit int32) ([]User, error) {
	rows, err := q.db.Query(ctx, listRecentUsers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.AvatarUrl,
			&i.GoogleID,
			&i.EmailVerified,
			&i.StripeCustomerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadsAdmin = `-- name: ListUploadsAdmin :many

SELECT id, workspace_id, project_id, user_id, keyword, keyword_normalized, thumbnail_s3_key, status, score, visibility_score, contrast_score, attention_score, mobile_score, branding_score, curiosity_score, cv_results, competitor_avg, suggestions, competitor_count, rank_in_competitors, error_message, retry_count, created_at, updated_at, deleted_at, relevance_score, relevance_reasoning, actual_ctr, published_at, file_size_bytes FROM analyses
WHERE ($3::bool OR deleted_at IS NULL)
  AND ($4::text = '' OR keyword ILIKE '%' || $4 || '%')
  AND ($5::text = '' OR status = $5)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUploadsAdminParams struct {
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
	IncludeDeleted bool   `json:"include_deleted"`
	Search         string `json:"search"`
	StatusFilter   string `json:"status_filter"`
}

// Upload management ---------------------------------------------------------
//
// include_deleted lets the admin list soft-deleted uploads too (needed to
// find something to restore); the customer-facing analyses list never does.
func (q *Queries) ListUploadsAdmin(ctx context.Context, arg ListUploadsAdminParams) ([]Analysis, error) {
	rows, err := q.db.Query(ctx, listUploadsAdmin,
		arg.Limit,
		arg.Offset,
		arg.IncludeDeleted,
		arg.Search,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Analysis{}
	for rows.Next() {
		var i Analysis
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.UserID,
			&i.Keyword,
			&i.KeywordNormalized,
			&i.ThumbnailS3Key,
			&i.Status,
			&i.Score,
			&i.VisibilityScore,
			&i.ContrastScore,
			&i.AttentionScore,
			&i.MobileScore,
			&i.BrandingScore,
			&i.CuriosityScore,
			&i.CvResults,
			&i.CompetitorAvg,
			&i.Suggestions,
			&i.CompetitorCount,
			&i.RankInCompetitors,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RelevanceScore,
			&i.RelevanceReasoning,
			&i.ActualCtr,
			&i.PublishedAt,
			&i.FileSizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserUploadsAdmin = `-- name: ListUserUploadsAdmin :many
SELECT id, workspace_id, project_id, user_id, keyword, keyword_normalized, thumbnail_s3_key, status, score, visibility_score, contrast_score, attention_score, mobile_score, branding_score, curiosity_score, cv_results, competitor_avg, suggestions, competitor_count, rank_in_competitors, error_message, retry_count, created_at, updated_at, deleted_at, relevance_score, relevance_reasoning, actual_ctr, published_at, file_size_bytes FROM analyses WHERE user_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListUserUploadsAdminParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListUserUploadsAdmin(ctx context.Context, arg ListUserUploadsAdminParams) ([]Analysis, error) {
	rows, err := q.db.Query(ctx, listUserUploadsAdmin, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Analysis{}
	for rows.Next() {
		var i Analysis
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.UserID,
			&i.Keyword,
			&i.KeywordNormalized,
			&i.ThumbnailS3Key,
			&i.Status,
			&i.Score,
			&i.VisibilityScore,
			&i.ContrastScore,
			&i.AttentionScore,
			&i.MobileScore,
			&i.BrandingScore,
			&i.CuriosityScore,
			&i.CvResults,
			&i.CompetitorAvg,
			&i.Suggestions,
			&i.CompetitorCount,
			&i.RankInCompetitors,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RelevanceScore,
			&i.RelevanceReasoning,
			&i.ActualCtr,
			&i.PublishedAt,
			&i.FileSizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersAdmin = `-- name: ListUsersAdmin :many

SELECT
    u.id, u.email, u.password_hash, u.full_name, u.avatar_url, u.google_id, u.email_verified, u.stripe_customer_id, u.created_at, u.updated_at, u.deleted_at, u.status,
    COALESCE(ws.plan, '') AS plan,
    COALESCE(agg.analyses_count, 0)::bigint AS analyses_count,
    COALESCE(agg.storage_used, 0)::bigint AS storage_used
FROM users u
LEFT JOIN LATERAL (
    SELECT w.plan FROM workspace_members wm
    JOIN workspaces w ON w.id = wm.workspace_id AND w.deleted_at IS NULL
    WHERE wm.user_id = u.id
    ORDER BY wm.joined_at ASC
    LIMIT 1
) ws ON true
LEFT JOIN LATERAL (
    SELECT COUNT(*) AS analyses_count, COALESCE(SUM(file_size_bytes), 0) AS storage_used
    FROM analyses
    WHERE analyses.user_id = u.id AND analyses.deleted_at IS NULL
) agg ON true
WHERE u.deleted_at IS NULL
  AND ($3::text = '' OR u.email ILIKE '%' || $3 || '%' OR u.full_name ILIKE '%' || $3 || '%')
  AND ($4::text = '' OR u.status = $4)
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersAdminParams struct {
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
	Search       string `json:"search"`
	StatusFilter string `json:"status_filter"`
}

type ListUsersAdminRow struct {
	ID               uuid.UUID          `json:"id"`
	Email            string             `json:"email"`
	PasswordHash     pgtype.Text        `json:"password_hash"`
	FullName         string             `json:"full_name"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	GoogleID         pgtype.Text        `json:"google_id"`
	EmailVerified    bool               `json:"email_verified"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	Status           string             `json:"status"`
	Plan             string             `json:"plan"`
	AnalysesCount    int64              `json:"analyses_count"`
	StorageUsed      int64              `json:"storage_used"`
}

// User management ---------------------------------------------------------
//
// ListUsersAdmin/GetUserDetailAdmin fold each user's primary-workspace plan
// and analyses/storage totals into the same query via LATERAL joins, instead
// of issuing 2-3 extra round-trips per user (avoids N+1 on the paginated
// list).
func (q *Queries) ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]ListUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersAdmin,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersAdminRow{}
	for rows.Next() {
		var i ListUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.AvatarUrl,
			&i.GoogleID,
			&i.EmailVerified,
			&i.StripeCustomerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Status,
			&i.Plan,
			&i.AnalysesCount,
			&i.StorageUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlySignupTrend = `-- name: MonthlySignupTrend :many
SELECT date_trunc('month', created_at)::date AS bucket, COUNT(*) AS count
FROM users
WHERE deleted_at IS NULL AND created_at >= NOW() - interval '12 months'
GROUP BY bucket
ORDER BY bucket
`

type MonthlySignupTrendRow struct {
	Bucket pgtype.Date `json:"bucket"`
	Count  int64       `json:"count"`
}

func (q *Queries) MonthlySignupTrend(ctx context.Context) ([]MonthlySignupTrendRow, error) {
	rows, err := q.db.Query(ctx, monthlySignupTrend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonthlySignupTrendRow{}
	for rows.Next() {
		var i MonthlySignupTrendRow
		if err := rows.Scan(&i.Bucket, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetUserPasswordAdmin = `-- name: ResetUserPasswordAdmin :exec
UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type ResetUserPasswordAdminParams struct {
	ID           uuid.UUID   `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) ResetUserPasswordAdmin(ctx context.Context, arg ResetUserPasswordAdminParams) error {
	_, err := q.db.Exec(ctx, resetUserPasswordAdmin, arg.ID, arg.PasswordHash)
	return err
}

const restoreUploadAdmin = `-- name: RestoreUploadAdmin :exec
UPDATE analyses SET deleted_at = NULL, updated_at = NOW() WHERE id = $1
`

func (q *Queries) RestoreUploadAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreUploadAdmin, id)
	return err
}

const revokeAdminRefreshToken = `-- name: RevokeAdminRefreshToken :exec
UPDATE admin_refresh_tokens SET is_revoked = TRUE WHERE token_hash = $1
`

func (q *Queries) RevokeAdminRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeAdminRefreshToken, tokenHash)
	return err
}

const softDeleteUploadAdmin = `-- name: SoftDeleteUploadAdmin :exec
UPDATE analyses SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteUploadAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUploadAdmin, id)
	return err
}

const softDeleteUserAdmin = `-- name: SoftDeleteUserAdmin :exec
UPDATE users SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteUserAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUserAdmin, id)
	return err
}

const sumStorageUsed = `-- name: SumStorageUsed :one
SELECT COALESCE(SUM(file_size_bytes), 0)::bigint FROM analyses WHERE deleted_at IS NULL
`

func (q *Queries) SumStorageUsed(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumStorageUsed)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const suspendUserAdmin = `-- name: SuspendUserAdmin :exec
UPDATE users SET status = 'suspended', updated_at = NOW() WHERE id = $1
`

func (q *Queries) SuspendUserAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, suspendUserAdmin, id)
	return err
}

const topActiveUsers = `-- name: TopActiveUsers :many
SELECT
    u.id, u.email, u.password_hash, u.full_name, u.avatar_url, u.google_id, u.email_verified, u.stripe_customer_id, u.created_at, u.updated_at, u.deleted_at, u.status,
    COALESCE(ws.plan, '') AS plan,
    COALESCE(agg.analyses_count, 0)::bigint AS analyses_count,
    COALESCE(agg.storage_used, 0)::bigint AS storage_used
FROM users u
LEFT JOIN LATERAL (
    SELECT w.plan FROM workspace_members wm
    JOIN workspaces w ON w.id = wm.workspace_id AND w.deleted_at IS NULL
    WHERE wm.user_id = u.id
    ORDER BY wm.joined_at ASC
    LIMIT 1
) ws ON true
JOIN LATERAL (
    SELECT COUNT(*) AS analyses_count, COALESCE(SUM(file_size_bytes), 0) AS storage_used
    FROM analyses
    WHERE analyses.user_id = u.id AND analyses.deleted_at IS NULL
) agg ON true
WHERE u.deleted_at IS NULL AND agg.analyses_count > 0
ORDER BY agg.analyses_count DESC
LIMIT $1
`

type TopActiveUsersRow struct {
	ID               uuid.UUID          `json:"id"`
	Email            string             `json:"email"`
	PasswordHash     pgtype.Text        `json:"password_hash"`
	FullName         string             `json:"full_name"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	GoogleID         pgtype.Text        `json:"google_id"`
	EmailVerified    bool               `json:"email_verified"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	Status           string             `json:"status"`
	Plan             string             `json:"plan"`
	AnalysesCount    int64              `json:"analyses_count"`
	StorageUsed      int64              `json:"storage_used"`
}

func (q *Queries) TopActiveUsers(ctx context.Context, limit int32) ([]TopActiveUsersRow, error) {
	rows, err := q.db.Query(ctx, topActiveUsers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopActiveUsersRow{}
	for rows.Next() {
		var i TopActiveUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.AvatarUrl,
			&i.GoogleID,
			&i.EmailVerified,
			&i.StripeCustomerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Status,
			&i.Plan,
			&i.AnalysesCount,
			&i.StorageUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminLastLogin = `-- name: UpdateAdminLastLogin :exec
UPDATE admin_users SET last_login_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateAdminLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAdminLastLogin, id)
	return err
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admin_users SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type UpdateAdminPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAdminPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateAppSettings = `-- name: UpdateAppSettings :one
UPDATE app_settings
SET
    max_upload_size_bytes = $1,
    allowed_extensions = $2,
    feature_flags = $3,
    storage_provider = $4,
    email_provider = $5,
    email_from_address = $6,
    updated_at = NOW()
WHERE id = 1
RETURNING id, max_upload_size_bytes, allowed_extensions, feature_flags, storage_provider, email_provider, email_from_address, updated_at
`

type UpdateAppSettingsParams struct {
	MaxUploadSizeBytes int64    `json:"max_upload_size_bytes"`
	AllowedExtensions  []string `json:"allowed_extensions"`
	FeatureFlags       []byte   `json:"feature_flags"`
	StorageProvider    string   `json:"storage_provider"`
	EmailProvider      string   `json:"email_provider"`
	EmailFromAddress   string   `json:"email_from_address"`
}

func (q *Queries) UpdateAppSettings(ctx context.Context, arg UpdateAppSettingsParams) (AppSetting, error) {
	row := q.db.QueryRow(ctx, updateAppSettings,
		arg.MaxUploadSizeBytes,
		arg.AllowedExtensions,
		arg.FeatureFlags,
		arg.StorageProvider,
		arg.EmailProvider,
		arg.EmailFromAddress,
	)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.MaxUploadSizeBytes,
		&i.AllowedExtensions,
		&i.FeatureFlags,
		&i.StorageProvider,
		&i.EmailProvider,
		&i.EmailFromAddress,
		&i.UpdatedAt,
	)
	return i, err
}
