// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analyses.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAnalysesByWorkspace = `-- name: CountAnalysesByWorkspace :one
SELECT COUNT(*) FROM analyses
WHERE workspace_id = $1 AND deleted_at IS NULL
  AND ($2::varchar IS NULL OR status = $2)
`

type CountAnalysesByWorkspaceParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	Status      pgtype.Text `json:"status"`
}

func (q *Queries) CountAnalysesByWorkspace(ctx context.Context, arg CountAnalysesByWorkspaceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAnalysesByWorkspace, arg.WorkspaceID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnalysis = `-- name: CreateAnalysis :one
INSERT INTO analyses (
    workspace_id, project_id, user_id, keyword, keyword_normalized, thumbnail_s3_key, status
) VALUES (
    $1, $2, $3, $4, $5, $6, 'pending'
) RETURNING id, workspace_id, project_id, user_id, keyword, keyword_normalized, thumbnail_s3_key, status, score, visibility_score, contrast_score, attention_score, mobile_score, branding_score, curiosity_score, cv_results, competitor_avg, suggestions, competitor_count, rank_in_competitors, error_message, retry_count, created_at, updated_at, deleted_at, relevance_score, relevance_reasoning
`

type CreateAnalysisParams struct {
	WorkspaceID       uuid.UUID   `json:"workspace_id"`
	ProjectID         pgtype.UUID `json:"project_id"`
	UserID            uuid.UUID   `json:"user_id"`
	Keyword           string      `json:"keyword"`
	KeywordNormalized string      `json:"keyword_normalized"`
	ThumbnailS3Key    string      `json:"thumbnail_s3_key"`
}

func (q *Queries) CreateAnalysis(ctx context.Context, arg CreateAnalysisParams) (Analysis, error) {
	row := q.db.QueryRow(ctx, createAnalysis,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.UserID,
		arg.Keyword,
		arg.KeywordNormalized,
		arg.ThumbnailS3Key,
	)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.UserID,
		&i.Keyword,
		&i.KeywordNormalized,
		&i.ThumbnailS3Key,
		&i.Status,
		&i.Score,
		&i.VisibilityScore,
		&i.ContrastScore,
		&i.AttentionScore,
		&i.MobileScore,
		&i.BrandingScore,
		&i.CuriosityScore,
		&i.CvResults,
		&i.CompetitorAvg,
		&i.Suggestions,
		&i.CompetitorCount,
		&i.RankInCompetitors,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RelevanceScore,
		&i.RelevanceReasoning,
	)
	return i, err
}

const createThumbnailVersion = `-- name: CreateThumbnailVersion :one
INSERT INTO thumbnail_versions (analysis_id, version_number, s3_key, score, cv_results)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, analysis_id, version_number, s3_key, score, cv_results, is_selected_winner, created_at
`

type CreateThumbnailVersionParams struct {
	AnalysisID    uuid.UUID   `json:"analysis_id"`
	VersionNumber int32       `json:"version_number"`
	S3Key         string      `json:"s3_key"`
	Score         pgtype.Int4 `json:"score"`
	CvResults     []byte      `json:"cv_results"`
}

func (q *Queries) CreateThumbnailVersion(ctx context.Context, arg CreateThumbnailVersionParams) (ThumbnailVersion, error) {
	row := q.db.QueryRow(ctx, createThumbnailVersion,
		arg.AnalysisID,
		arg.VersionNumber,
		arg.S3Key,
		arg.Score,
		arg.CvResults,
	)
	var i ThumbnailVersion
	err := row.Scan(
		&i.ID,
		&i.AnalysisID,
		&i.VersionNumber,
		&i.S3Key,
		&i.Score,
		&i.CvResults,
		&i.IsSelectedWinner,
		&i.CreatedAt,
	)
	return i, err
}

const getAnalysisByID = `-- name: GetAnalysisByID :one
SELECT id, workspace_id, project_id, user_id, keyword, keyword_normalized, thumbnail_s3_key, status, score, visibility_score, contrast_score, attention_score, mobile_score, branding_score, curiosity_score, cv_results, competitor_avg, suggestions, competitor_count, rank_in_competitors, error_message, retry_count, created_at, updated_at, deleted_at, relevance_score, relevance_reasoning FROM analyses WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAnalysisByID(ctx context.Context, id uuid.UUID) (Analysis, error) {
	row := q.db.QueryRow(ctx, getAnalysisByID, id)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.UserID,
		&i.Keyword,
		&i.KeywordNormalized,
		&i.ThumbnailS3Key,
		&i.Status,
		&i.Score,
		&i.VisibilityScore,
		&i.ContrastScore,
		&i.AttentionScore,
		&i.MobileScore,
		&i.BrandingScore,
		&i.CuriosityScore,
		&i.CvResults,
		&i.CompetitorAvg,
		&i.Suggestions,
		&i.CompetitorCount,
		&i.RankInCompetitors,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RelevanceScore,
		&i.RelevanceReasoning,
	)
	return i, err
}

const listAnalysesByWorkspace = `-- name: ListAnalysesByWorkspace :many
SELECT id, workspace_id, project_id, user_id, keyword, keyword_normalized, thumbnail_s3_key, status, score, visibility_score, contrast_score, attention_score, mobile_score, branding_score, curiosity_score, cv_results, competitor_avg, suggestions, competitor_count, rank_in_competitors, error_message, retry_count, created_at, updated_at, deleted_at, relevance_score, relevance_reasoning FROM analyses
WHERE workspace_id = $1 AND deleted_at IS NULL
  AND ($4::varchar IS NULL OR status = $4)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAnalysesByWorkspaceParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	Status      pgtype.Text `json:"status"`
}

func (q *Queries) ListAnalysesByWorkspace(ctx context.Context, arg ListAnalysesByWorkspaceParams) ([]Analysis, error) {
	rows, err := q.db.Query(ctx, listAnalysesByWorkspace,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Analysis{}
	for rows.Next() {
		var i Analysis
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.UserID,
			&i.Keyword,
			&i.KeywordNormalized,
			&i.ThumbnailS3Key,
			&i.Status,
			&i.Score,
			&i.VisibilityScore,
			&i.ContrastScore,
			&i.AttentionScore,
			&i.MobileScore,
			&i.BrandingScore,
			&i.CuriosityScore,
			&i.CvResults,
			&i.CompetitorAvg,
			&i.Suggestions,
			&i.CompetitorCount,
			&i.RankInCompetitors,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RelevanceScore,
			&i.RelevanceReasoning,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThumbnailVersions = `-- name: ListThumbnailVersions :many
SELECT id, analysis_id, version_number, s3_key, score, cv_results, is_selected_winner, created_at FROM thumbnail_versions WHERE analysis_id = $1 ORDER BY version_number
`

func (q *Queries) ListThumbnailVersions(ctx context.Context, analysisID uuid.UUID) ([]ThumbnailVersion, error) {
	rows, err := q.db.Query(ctx, listThumbnailVersions, analysisID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThumbnailVersion{}
	for rows.Next() {
		var i ThumbnailVersion
		if err := rows.Scan(
			&i.ID,
			&i.AnalysisID,
			&i.VersionNumber,
			&i.S3Key,
			&i.Score,
			&i.CvResults,
			&i.IsSelectedWinner,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextThumbnailVersionNumber = `-- name: NextThumbnailVersionNumber :one
SELECT COALESCE(MAX(version_number), 0) + 1 FROM thumbnail_versions WHERE analysis_id = $1
`

func (q *Queries) NextThumbnailVersionNumber(ctx context.Context, analysisID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextThumbnailVersionNumber, analysisID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const updateAnalysisResults = `-- name: UpdateAnalysisResults :one
UPDATE analyses
SET
    status = 'complete',
    score = $2,
    visibility_score = $3,
    contrast_score = $4,
    attention_score = $5,
    mobile_score = $6,
    branding_score = $7,
    curiosity_score = $8,
    cv_results = $9,
    competitor_avg = $10,
    suggestions = $11,
    competitor_count = $12,
    rank_in_competitors = $13,
    relevance_score = $14,
    relevance_reasoning = $15,
    updated_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, project_id, user_id, keyword, keyword_normalized, thumbnail_s3_key, status, score, visibility_score, contrast_score, attention_score, mobile_score, branding_score, curiosity_score, cv_results, competitor_avg, suggestions, competitor_count, rank_in_competitors, error_message, retry_count, created_at, updated_at, deleted_at, relevance_score, relevance_reasoning
`

type UpdateAnalysisResultsParams struct {
	ID                 uuid.UUID   `json:"id"`
	Score              pgtype.Int4 `json:"score"`
	VisibilityScore    pgtype.Int4 `json:"visibility_score"`
	ContrastScore      pgtype.Int4 `json:"contrast_score"`
	AttentionScore     pgtype.Int4 `json:"attention_score"`
	MobileScore        pgtype.Int4 `json:"mobile_score"`
	BrandingScore      pgtype.Int4 `json:"branding_score"`
	CuriosityScore     pgtype.Int4 `json:"curiosity_score"`
	CvResults          []byte      `json:"cv_results"`
	CompetitorAvg      []byte      `json:"competitor_avg"`
	Suggestions        []byte      `json:"suggestions"`
	CompetitorCount    pgtype.Int4 `json:"competitor_count"`
	RankInCompetitors  pgtype.Int4 `json:"rank_in_competitors"`
	RelevanceScore     pgtype.Int4 `json:"relevance_score"`
	RelevanceReasoning pgtype.Text `json:"relevance_reasoning"`
}

func (q *Queries) UpdateAnalysisResults(ctx context.Context, arg UpdateAnalysisResultsParams) (Analysis, error) {
	row := q.db.QueryRow(ctx, updateAnalysisResults,
		arg.ID,
		arg.Score,
		arg.VisibilityScore,
		arg.ContrastScore,
		arg.AttentionScore,
		arg.MobileScore,
		arg.BrandingScore,
		arg.CuriosityScore,
		arg.CvResults,
		arg.CompetitorAvg,
		arg.Suggestions,
		arg.CompetitorCount,
		arg.RankInCompetitors,
		arg.RelevanceScore,
		arg.RelevanceReasoning,
	)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.UserID,
		&i.Keyword,
		&i.KeywordNormalized,
		&i.ThumbnailS3Key,
		&i.Status,
		&i.Score,
		&i.VisibilityScore,
		&i.ContrastScore,
		&i.AttentionScore,
		&i.MobileScore,
		&i.BrandingScore,
		&i.CuriosityScore,
		&i.CvResults,
		&i.CompetitorAvg,
		&i.Suggestions,
		&i.CompetitorCount,
		&i.RankInCompetitors,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RelevanceScore,
		&i.RelevanceReasoning,
	)
	return i, err
}

const updateAnalysisStatus = `-- name: UpdateAnalysisStatus :one
UPDATE analyses
SET status = $2, error_message = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, project_id, user_id, keyword, keyword_normalized, thumbnail_s3_key, status, score, visibility_score, contrast_score, attention_score, mobile_score, branding_score, curiosity_score, cv_results, competitor_avg, suggestions, competitor_count, rank_in_competitors, error_message, retry_count, created_at, updated_at, deleted_at, relevance_score, relevance_reasoning
`

type UpdateAnalysisStatusParams struct {
	ID           uuid.UUID   `json:"id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateAnalysisStatus(ctx context.Context, arg UpdateAnalysisStatusParams) (Analysis, error) {
	row := q.db.QueryRow(ctx, updateAnalysisStatus, arg.ID, arg.Status, arg.ErrorMessage)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.UserID,
		&i.Keyword,
		&i.KeywordNormalized,
		&i.ThumbnailS3Key,
		&i.Status,
		&i.Score,
		&i.VisibilityScore,
		&i.ContrastScore,
		&i.AttentionScore,
		&i.MobileScore,
		&i.BrandingScore,
		&i.CuriosityScore,
		&i.CvResults,
		&i.CompetitorAvg,
		&i.Suggestions,
		&i.CompetitorCount,
		&i.RankInCompetitors,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RelevanceScore,
		&i.RelevanceReasoning,
	)
	return i, err
}
