// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (workspace_id, name, key_hash, key_prefix, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, name, key_hash, key_prefix, requests_this_month, requests_limit, last_used_at, expires_at, created_by, created_at, revoked_at
`

type CreateApiKeyParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	KeyHash     string    `json:"key_hash"`
	KeyPrefix   string    `json:"key_prefix"`
	CreatedBy   uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.WorkspaceID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.CreatedBy,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.RequestsThisMonth,
		&i.RequestsLimit,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, workspace_id, name, key_hash, key_prefix, requests_this_month, requests_limit, last_used_at, expires_at, created_by, created_at, revoked_at FROM api_keys WHERE key_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.RequestsThisMonth,
		&i.RequestsLimit,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSubscriptionByWorkspace = `-- name: GetSubscriptionByWorkspace :one
SELECT id, workspace_id, stripe_subscription_id, stripe_price_id, plan, status, current_period_start, current_period_end, cancel_at, canceled_at, created_at, updated_at FROM subscriptions WHERE workspace_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetSubscriptionByWorkspace(ctx context.Context, workspaceID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByWorkspace, workspaceID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.StripeSubscriptionID,
		&i.StripePriceID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApiKeysByWorkspace = `-- name: ListApiKeysByWorkspace :many
SELECT id, workspace_id, name, key_hash, key_prefix, requests_this_month, requests_limit, last_used_at, expires_at, created_by, created_at, revoked_at FROM api_keys WHERE workspace_id = $1 AND revoked_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListApiKeysByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listApiKeysByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.RequestsThisMonth,
			&i.RequestsLimit,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiKey = `-- name: RevokeApiKey :exec
UPDATE api_keys SET revoked_at = NOW() WHERE id = $1 AND workspace_id = $2
`

type RevokeApiKeyParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) RevokeApiKey(ctx context.Context, arg RevokeApiKeyParams) error {
	_, err := q.db.Exec(ctx, revokeApiKey, arg.ID, arg.WorkspaceID)
	return err
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO subscriptions (workspace_id, stripe_subscription_id, stripe_price_id, plan, status, current_period_start, current_period_end)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (stripe_subscription_id) DO UPDATE
SET plan = EXCLUDED.plan, status = EXCLUDED.status,
    current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end,
    updated_at = NOW()
RETURNING id, workspace_id, stripe_subscription_id, stripe_price_id, plan, status, current_period_start, current_period_end, cancel_at, canceled_at, created_at, updated_at
`

type UpsertSubscriptionParams struct {
	WorkspaceID          uuid.UUID          `json:"workspace_id"`
	StripeSubscriptionID string             `json:"stripe_subscription_id"`
	StripePriceID        string             `json:"stripe_price_id"`
	Plan                 string             `json:"plan"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.WorkspaceID,
		arg.StripeSubscriptionID,
		arg.StripePriceID,
		arg.Plan,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.StripeSubscriptionID,
		&i.StripePriceID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
