// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competitors.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCompetitorSnapshot = `-- name: CreateCompetitorSnapshot :one
INSERT INTO competitor_snapshots (
    analysis_id, tracking_job_id, video_id, video_title, channel_id, channel_name,
    thumbnail_url, view_count, like_count, subscriber_count, rank_position, keyword, cv_results, score
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, analysis_id, tracking_job_id, video_id, video_title, channel_id, channel_name, thumbnail_url, thumbnail_s3_key, view_count, like_count, subscriber_count, rank_position, keyword, cv_results, score, snapshot_date, created_at
`

type CreateCompetitorSnapshotParams struct {
	AnalysisID      pgtype.UUID `json:"analysis_id"`
	TrackingJobID   pgtype.UUID `json:"tracking_job_id"`
	VideoID         string      `json:"video_id"`
	VideoTitle      string      `json:"video_title"`
	ChannelID       string      `json:"channel_id"`
	ChannelName     string      `json:"channel_name"`
	ThumbnailUrl    string      `json:"thumbnail_url"`
	ViewCount       pgtype.Int8 `json:"view_count"`
	LikeCount       pgtype.Int8 `json:"like_count"`
	SubscriberCount pgtype.Int8 `json:"subscriber_count"`
	RankPosition    pgtype.Int4 `json:"rank_position"`
	Keyword         pgtype.Text `json:"keyword"`
	CvResults       []byte      `json:"cv_results"`
	Score           pgtype.Int4 `json:"score"`
}

func (q *Queries) CreateCompetitorSnapshot(ctx context.Context, arg CreateCompetitorSnapshotParams) (CompetitorSnapshot, error) {
	row := q.db.QueryRow(ctx, createCompetitorSnapshot,
		arg.AnalysisID,
		arg.TrackingJobID,
		arg.VideoID,
		arg.VideoTitle,
		arg.ChannelID,
		arg.ChannelName,
		arg.ThumbnailUrl,
		arg.ViewCount,
		arg.LikeCount,
		arg.SubscriberCount,
		arg.RankPosition,
		arg.Keyword,
		arg.CvResults,
		arg.Score,
	)
	var i CompetitorSnapshot
	err := row.Scan(
		&i.ID,
		&i.AnalysisID,
		&i.TrackingJobID,
		&i.VideoID,
		&i.VideoTitle,
		&i.ChannelID,
		&i.ChannelName,
		&i.ThumbnailUrl,
		&i.ThumbnailS3Key,
		&i.ViewCount,
		&i.LikeCount,
		&i.SubscriberCount,
		&i.RankPosition,
		&i.Keyword,
		&i.CvResults,
		&i.Score,
		&i.SnapshotDate,
		&i.CreatedAt,
	)
	return i, err
}

const createTrackingJob = `-- name: CreateTrackingJob :one
INSERT INTO tracking_jobs (workspace_id, type, channel_id, keyword, check_interval_hours, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, type, channel_id, keyword, status, check_interval_hours, last_checked_at, next_check_at, created_by, created_at, updated_at
`

type CreateTrackingJobParams struct {
	WorkspaceID        uuid.UUID   `json:"workspace_id"`
	Type               string      `json:"type"`
	ChannelID          pgtype.Text `json:"channel_id"`
	Keyword            pgtype.Text `json:"keyword"`
	CheckIntervalHours int32       `json:"check_interval_hours"`
	CreatedBy          uuid.UUID   `json:"created_by"`
}

func (q *Queries) CreateTrackingJob(ctx context.Context, arg CreateTrackingJobParams) (TrackingJob, error) {
	row := q.db.QueryRow(ctx, createTrackingJob,
		arg.WorkspaceID,
		arg.Type,
		arg.ChannelID,
		arg.Keyword,
		arg.CheckIntervalHours,
		arg.CreatedBy,
	)
	var i TrackingJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.ChannelID,
		&i.Keyword,
		&i.Status,
		&i.CheckIntervalHours,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompetitorsByAnalysis = `-- name: ListCompetitorsByAnalysis :many
SELECT id, analysis_id, tracking_job_id, video_id, video_title, channel_id, channel_name, thumbnail_url, thumbnail_s3_key, view_count, like_count, subscriber_count, rank_position, keyword, cv_results, score, snapshot_date, created_at FROM competitor_snapshots WHERE analysis_id = $1 ORDER BY rank_position
`

func (q *Queries) ListCompetitorsByAnalysis(ctx context.Context, analysisID pgtype.UUID) ([]CompetitorSnapshot, error) {
	rows, err := q.db.Query(ctx, listCompetitorsByAnalysis, analysisID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompetitorSnapshot{}
	for rows.Next() {
		var i CompetitorSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AnalysisID,
			&i.TrackingJobID,
			&i.VideoID,
			&i.VideoTitle,
			&i.ChannelID,
			&i.ChannelName,
			&i.ThumbnailUrl,
			&i.ThumbnailS3Key,
			&i.ViewCount,
			&i.LikeCount,
			&i.SubscriberCount,
			&i.RankPosition,
			&i.Keyword,
			&i.CvResults,
			&i.Score,
			&i.SnapshotDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueTrackingJobs = `-- name: ListDueTrackingJobs :many
SELECT id, workspace_id, type, channel_id, keyword, status, check_interval_hours, last_checked_at, next_check_at, created_by, created_at, updated_at FROM tracking_jobs WHERE status = 'active' AND next_check_at <= NOW()
`

func (q *Queries) ListDueTrackingJobs(ctx context.Context) ([]TrackingJob, error) {
	rows, err := q.db.Query(ctx, listDueTrackingJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingJob{}
	for rows.Next() {
		var i TrackingJob
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Type,
			&i.ChannelID,
			&i.Keyword,
			&i.Status,
			&i.CheckIntervalHours,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestCompetitorsByKeyword = `-- name: ListLatestCompetitorsByKeyword :many
SELECT id, analysis_id, tracking_job_id, video_id, video_title, channel_id, channel_name, thumbnail_url, thumbnail_s3_key, view_count, like_count, subscriber_count, rank_position, keyword, cv_results, score, snapshot_date, created_at FROM competitor_snapshots
WHERE keyword = $1
ORDER BY snapshot_date DESC, rank_position
LIMIT $2
`

type ListLatestCompetitorsByKeywordParams struct {
	Keyword pgtype.Text `json:"keyword"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) ListLatestCompetitorsByKeyword(ctx context.Context, arg ListLatestCompetitorsByKeywordParams) ([]CompetitorSnapshot, error) {
	rows, err := q.db.Query(ctx, listLatestCompetitorsByKeyword, arg.Keyword, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompetitorSnapshot{}
	for rows.Next() {
		var i CompetitorSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AnalysisID,
			&i.TrackingJobID,
			&i.VideoID,
			&i.VideoTitle,
			&i.ChannelID,
			&i.ChannelName,
			&i.ThumbnailUrl,
			&i.ThumbnailS3Key,
			&i.ViewCount,
			&i.LikeCount,
			&i.SubscriberCount,
			&i.RankPosition,
			&i.Keyword,
			&i.CvResults,
			&i.Score,
			&i.SnapshotDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackingJobsByWorkspace = `-- name: ListTrackingJobsByWorkspace :many
SELECT id, workspace_id, type, channel_id, keyword, status, check_interval_hours, last_checked_at, next_check_at, created_by, created_at, updated_at FROM tracking_jobs WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTrackingJobsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]TrackingJob, error) {
	rows, err := q.db.Query(ctx, listTrackingJobsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingJob{}
	for rows.Next() {
		var i TrackingJob
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Type,
			&i.ChannelID,
			&i.Keyword,
			&i.Status,
			&i.CheckIntervalHours,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTrackingJobChecked = `-- name: MarkTrackingJobChecked :exec
UPDATE tracking_jobs
SET last_checked_at = NOW(), next_check_at = NOW() + (check_interval_hours || ' hours')::interval, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkTrackingJobChecked(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTrackingJobChecked, id)
	return err
}
