// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verification.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailVerificationCode = `-- name: ConsumeEmailVerificationCode :exec
UPDATE email_verification_codes SET consumed_at = NOW() WHERE id = $1
`

func (q *Queries) ConsumeEmailVerificationCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeEmailVerificationCode, id)
	return err
}

const createEmailVerificationCode = `-- name: CreateEmailVerificationCode :one
INSERT INTO email_verification_codes (user_id, code_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, code_hash, attempts, expires_at, consumed_at, created_at
`

type CreateEmailVerificationCodeParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailVerificationCode(ctx context.Context, arg CreateEmailVerificationCodeParams) (EmailVerificationCode, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationCode, arg.UserID, arg.CodeHash, arg.ExpiresAt)
	var i EmailVerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestEmailVerificationCode = `-- name: GetLatestEmailVerificationCode :one
SELECT id, user_id, code_hash, attempts, expires_at, consumed_at, created_at FROM email_verification_codes
WHERE user_id = $1 AND consumed_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestEmailVerificationCode(ctx context.Context, userID uuid.UUID) (EmailVerificationCode, error) {
	row := q.db.QueryRow(ctx, getLatestEmailVerificationCode, userID)
	var i EmailVerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementEmailVerificationAttempts = `-- name: IncrementEmailVerificationAttempts :exec
UPDATE email_verification_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementEmailVerificationAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementEmailVerificationAttempts, id)
	return err
}

const invalidateEmailVerificationCodes = `-- name: InvalidateEmailVerificationCodes :exec
UPDATE email_verification_codes SET consumed_at = NOW()
WHERE user_id = $1 AND consumed_at IS NULL
`

func (q *Queries) InvalidateEmailVerificationCodes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidateEmailVerificationCodes, userID)
	return err
}
