// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Analysis struct {
	ID                uuid.UUID          `json:"id"`
	WorkspaceID       uuid.UUID          `json:"workspace_id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	UserID            uuid.UUID          `json:"user_id"`
	Keyword           string             `json:"keyword"`
	KeywordNormalized string             `json:"keyword_normalized"`
	ThumbnailUrl      string             `json:"thumbnail_url"`
	ThumbnailS3Key    string             `json:"thumbnail_s3_key"`
	Status            string             `json:"status"`
	Score             pgtype.Int4        `json:"score"`
	VisibilityScore   pgtype.Int4        `json:"visibility_score"`
	ContrastScore     pgtype.Int4        `json:"contrast_score"`
	AttentionScore    pgtype.Int4        `json:"attention_score"`
	MobileScore       pgtype.Int4        `json:"mobile_score"`
	BrandingScore     pgtype.Int4        `json:"branding_score"`
	CuriosityScore    pgtype.Int4        `json:"curiosity_score"`
	CvResults         []byte             `json:"cv_results"`
	CompetitorAvg     []byte             `json:"competitor_avg"`
	Suggestions       []byte             `json:"suggestions"`
	CompetitorCount   pgtype.Int4        `json:"competitor_count"`
	RankInCompetitors pgtype.Int4        `json:"rank_in_competitors"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
	RetryCount        pgtype.Int4        `json:"retry_count"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type ApiKey struct {
	ID                uuid.UUID          `json:"id"`
	WorkspaceID       uuid.UUID          `json:"workspace_id"`
	Name              string             `json:"name"`
	KeyHash           string             `json:"key_hash"`
	KeyPrefix         string             `json:"key_prefix"`
	RequestsThisMonth int32              `json:"requests_this_month"`
	RequestsLimit     int32              `json:"requests_limit"`
	LastUsedAt        pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedBy         uuid.UUID          `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
}

type Comment struct {
	ID         uuid.UUID          `json:"id"`
	AnalysisID uuid.UUID          `json:"analysis_id"`
	UserID     uuid.UUID          `json:"user_id"`
	ParentID   pgtype.UUID        `json:"parent_id"`
	Body       string             `json:"body"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type CompetitorSnapshot struct {
	ID              uuid.UUID          `json:"id"`
	AnalysisID      pgtype.UUID        `json:"analysis_id"`
	TrackingJobID   pgtype.UUID        `json:"tracking_job_id"`
	VideoID         string             `json:"video_id"`
	VideoTitle      string             `json:"video_title"`
	ChannelID       string             `json:"channel_id"`
	ChannelName     string             `json:"channel_name"`
	ThumbnailUrl    string             `json:"thumbnail_url"`
	ThumbnailS3Key  pgtype.Text        `json:"thumbnail_s3_key"`
	ViewCount       pgtype.Int8        `json:"view_count"`
	LikeCount       pgtype.Int8        `json:"like_count"`
	SubscriberCount pgtype.Int8        `json:"subscriber_count"`
	RankPosition    pgtype.Int4        `json:"rank_position"`
	Keyword         pgtype.Text        `json:"keyword"`
	CvResults       []byte             `json:"cv_results"`
	Score           pgtype.Int4        `json:"score"`
	SnapshotDate    pgtype.Date        `json:"snapshot_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Color       pgtype.Text        `json:"color"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type RefreshToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	DeviceInfo pgtype.Text        `json:"device_info"`
	IsRevoked  bool               `json:"is_revoked"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID                   uuid.UUID          `json:"id"`
	WorkspaceID          uuid.UUID          `json:"workspace_id"`
	StripeSubscriptionID string             `json:"stripe_subscription_id"`
	StripePriceID        string             `json:"stripe_price_id"`
	Plan                 string             `json:"plan"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	CancelAt             pgtype.Timestamptz `json:"cancel_at"`
	CanceledAt           pgtype.Timestamptz `json:"canceled_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type ThumbnailVersion struct {
	ID               uuid.UUID          `json:"id"`
	AnalysisID       uuid.UUID          `json:"analysis_id"`
	VersionNumber    int32              `json:"version_number"`
	S3Key            string             `json:"s3_key"`
	ThumbnailUrl     string             `json:"thumbnail_url"`
	Score            pgtype.Int4        `json:"score"`
	CvResults        []byte             `json:"cv_results"`
	IsSelectedWinner pgtype.Bool        `json:"is_selected_winner"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type TrackingJob struct {
	ID                 uuid.UUID          `json:"id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	Type               string             `json:"type"`
	ChannelID          pgtype.Text        `json:"channel_id"`
	Keyword            pgtype.Text        `json:"keyword"`
	Status             string             `json:"status"`
	CheckIntervalHours int32              `json:"check_interval_hours"`
	LastCheckedAt      pgtype.Timestamptz `json:"last_checked_at"`
	NextCheckAt        pgtype.Timestamptz `json:"next_check_at"`
	CreatedBy          uuid.UUID          `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID               uuid.UUID          `json:"id"`
	Email            string             `json:"email"`
	PasswordHash     pgtype.Text        `json:"password_hash"`
	FullName         string             `json:"full_name"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	GoogleID         pgtype.Text        `json:"google_id"`
	EmailVerified    bool               `json:"email_verified"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type ViralThumbnail struct {
	ID                    uuid.UUID          `json:"id"`
	VideoID               string             `json:"video_id"`
	ChannelID             string             `json:"channel_id"`
	ChannelName           string             `json:"channel_name"`
	VideoTitle            string             `json:"video_title"`
	ThumbnailUrl          string             `json:"thumbnail_url"`
	ThumbnailS3Key        pgtype.Text        `json:"thumbnail_s3_key"`
	Niche                 pgtype.Text        `json:"niche"`
	Tags                  []string           `json:"tags"`
	ViewCount             pgtype.Int8        `json:"view_count"`
	ViewCountWhenCaptured pgtype.Int8        `json:"view_count_when_captured"`
	Score                 pgtype.Int4        `json:"score"`
	HasFace               bool               `json:"has_face"`
	CvResults             []byte             `json:"cv_results"`
	CapturedAt            pgtype.Timestamptz `json:"captured_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type Workspace struct {
	ID                   uuid.UUID          `json:"id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	LogoUrl              pgtype.Text        `json:"logo_url"`
	Plan                 string             `json:"plan"`
	OwnerID              uuid.UUID          `json:"owner_id"`
	AnalysesThisMonth    int32              `json:"analyses_this_month"`
	AnalysesLimit        int32              `json:"analyses_limit"`
	ApiRequestsThisMonth int32              `json:"api_requests_this_month"`
	ApiRequestsLimit     int32              `json:"api_requests_limit"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type WorkspaceMember struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}
