// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordResetCode = `-- name: ConsumePasswordResetCode :exec
UPDATE password_reset_codes SET consumed_at = NOW() WHERE id = $1
`

func (q *Queries) ConsumePasswordResetCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumePasswordResetCode, id)
	return err
}

const createPasswordResetCode = `-- name: CreatePasswordResetCode :one
INSERT INTO password_reset_codes (user_id, code_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, code_hash, attempts, expires_at, consumed_at, created_at
`

type CreatePasswordResetCodeParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetCode(ctx context.Context, arg CreatePasswordResetCodeParams) (PasswordResetCode, error) {
	row := q.db.QueryRow(ctx, createPasswordResetCode, arg.UserID, arg.CodeHash, arg.ExpiresAt)
	var i PasswordResetCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPasswordResetCode = `-- name: GetLatestPasswordResetCode :one
SELECT id, user_id, code_hash, attempts, expires_at, consumed_at, created_at FROM password_reset_codes
WHERE user_id = $1 AND consumed_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestPasswordResetCode(ctx context.Context, userID uuid.UUID) (PasswordResetCode, error) {
	row := q.db.QueryRow(ctx, getLatestPasswordResetCode, userID)
	var i PasswordResetCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementPasswordResetAttempts = `-- name: IncrementPasswordResetAttempts :exec
UPDATE password_reset_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementPasswordResetAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementPasswordResetAttempts, id)
	return err
}

const invalidatePasswordResetCodes = `-- name: InvalidatePasswordResetCodes :exec
UPDATE password_reset_codes SET consumed_at = NOW()
WHERE user_id = $1 AND consumed_at IS NULL
`

func (q *Queries) InvalidatePasswordResetCodes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidatePasswordResetCodes, userID)
	return err
}
