// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error)
	CountAnalysesByWorkspace(ctx context.Context, arg CountAnalysesByWorkspaceParams) (int64, error)
	CreateAnalysis(ctx context.Context, arg CreateAnalysisParams) (Analysis, error)
	CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error)
	CreateCompetitorSnapshot(ctx context.Context, arg CreateCompetitorSnapshotParams) (CompetitorSnapshot, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateThumbnailVersion(ctx context.Context, arg CreateThumbnailVersionParams) (ThumbnailVersion, error)
	CreateTrackingJob(ctx context.Context, arg CreateTrackingJobParams) (TrackingJob, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	GetAnalysisByID(ctx context.Context, id uuid.UUID) (Analysis, error)
	GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetSubscriptionByWorkspace(ctx context.Context, workspaceID uuid.UUID) (Subscription, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error)
	IncrementWorkspaceAnalysesUsage(ctx context.Context, id uuid.UUID) error
	ListAnalysesByWorkspace(ctx context.Context, arg ListAnalysesByWorkspaceParams) ([]Analysis, error)
	ListApiKeysByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ApiKey, error)
	ListCompetitorsByAnalysis(ctx context.Context, analysisID pgtype.UUID) ([]CompetitorSnapshot, error)
	ListDueTrackingJobs(ctx context.Context) ([]TrackingJob, error)
	ListLatestCompetitorsByKeyword(ctx context.Context, arg ListLatestCompetitorsByKeywordParams) ([]CompetitorSnapshot, error)
	ListThumbnailVersions(ctx context.Context, analysisID uuid.UUID) ([]ThumbnailVersion, error)
	ListTrackingJobsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]TrackingJob, error)
	ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersRow, error)
	ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]Workspace, error)
	MarkTrackingJobChecked(ctx context.Context, id uuid.UUID) error
	NextThumbnailVersionNumber(ctx context.Context, analysisID uuid.UUID) (int32, error)
	RevokeApiKey(ctx context.Context, arg RevokeApiKeyParams) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	SearchViralThumbnails(ctx context.Context, arg SearchViralThumbnailsParams) ([]ViralThumbnail, error)
	UpdateAnalysisResults(ctx context.Context, arg UpdateAnalysisResultsParams) (Analysis, error)
	UpdateAnalysisStatus(ctx context.Context, arg UpdateAnalysisStatusParams) (Analysis, error)
	UpdateWorkspacePlan(ctx context.Context, arg UpdateWorkspacePlanParams) (Workspace, error)
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error)
	UpsertViralThumbnail(ctx context.Context, arg UpsertViralThumbnailParams) (ViralThumbnail, error)
}

var _ Querier = (*Queries)(nil)
