// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: viral_thumbnails.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchViralThumbnails = `-- name: SearchViralThumbnails :many
SELECT id, video_id, channel_id, channel_name, video_title, thumbnail_url, thumbnail_s3_key, niche, tags, view_count, view_count_when_captured, score, has_face, cv_results, captured_at, created_at FROM viral_thumbnails
WHERE ($3::text IS NULL OR tags @> ARRAY[$3::text])
  AND ($4::varchar IS NULL OR niche = $4)
  AND ($5::int IS NULL OR score >= $5)
  AND ($6::bool IS NULL OR has_face = $6)
ORDER BY score DESC
LIMIT $1 OFFSET $2
`

type SearchViralThumbnailsParams struct {
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Keyword  pgtype.Text `json:"keyword"`
	Niche    pgtype.Text `json:"niche"`
	MinScore pgtype.Int4 `json:"min_score"`
	HasFace  pgtype.Bool `json:"has_face"`
}

func (q *Queries) SearchViralThumbnails(ctx context.Context, arg SearchViralThumbnailsParams) ([]ViralThumbnail, error) {
	rows, err := q.db.Query(ctx, searchViralThumbnails,
		arg.Limit,
		arg.Offset,
		arg.Keyword,
		arg.Niche,
		arg.MinScore,
		arg.HasFace,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ViralThumbnail{}
	for rows.Next() {
		var i ViralThumbnail
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.ChannelID,
			&i.ChannelName,
			&i.VideoTitle,
			&i.ThumbnailUrl,
			&i.ThumbnailS3Key,
			&i.Niche,
			&i.Tags,
			&i.ViewCount,
			&i.ViewCountWhenCaptured,
			&i.Score,
			&i.HasFace,
			&i.CvResults,
			&i.CapturedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertViralThumbnail = `-- name: UpsertViralThumbnail :one
INSERT INTO viral_thumbnails (video_id, channel_id, channel_name, video_title, thumbnail_url, niche, tags, view_count, score, has_face, cv_results)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (video_id) DO UPDATE
SET score = EXCLUDED.score,
    view_count = EXCLUDED.view_count,
    cv_results = EXCLUDED.cv_results,
    tags = (SELECT array_agg(DISTINCT tag) FROM unnest(viral_thumbnails.tags || EXCLUDED.tags) AS tag),
    niche = COALESCE(viral_thumbnails.niche, EXCLUDED.niche),
    has_face = EXCLUDED.has_face
RETURNING id, video_id, channel_id, channel_name, video_title, thumbnail_url, thumbnail_s3_key, niche, tags, view_count, view_count_when_captured, score, has_face, cv_results, captured_at, created_at
`

type UpsertViralThumbnailParams struct {
	VideoID      string      `json:"video_id"`
	ChannelID    string      `json:"channel_id"`
	ChannelName  string      `json:"channel_name"`
	VideoTitle   string      `json:"video_title"`
	ThumbnailUrl string      `json:"thumbnail_url"`
	Niche        pgtype.Text `json:"niche"`
	Tags         []string    `json:"tags"`
	ViewCount    pgtype.Int8 `json:"view_count"`
	Score        pgtype.Int4 `json:"score"`
	HasFace      bool        `json:"has_face"`
	CvResults    []byte      `json:"cv_results"`
}

func (q *Queries) UpsertViralThumbnail(ctx context.Context, arg UpsertViralThumbnailParams) (ViralThumbnail, error) {
	row := q.db.QueryRow(ctx, upsertViralThumbnail,
		arg.VideoID,
		arg.ChannelID,
		arg.ChannelName,
		arg.VideoTitle,
		arg.ThumbnailUrl,
		arg.Niche,
		arg.Tags,
		arg.ViewCount,
		arg.Score,
		arg.HasFace,
		arg.CvResults,
	)
	var i ViralThumbnail
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.ChannelID,
		&i.ChannelName,
		&i.VideoTitle,
		&i.ThumbnailUrl,
		&i.ThumbnailS3Key,
		&i.Niche,
		&i.Tags,
		&i.ViewCount,
		&i.ViewCountWhenCaptured,
		&i.Score,
		&i.HasFace,
		&i.CvResults,
		&i.CapturedAt,
		&i.CreatedAt,
	)
	return i, err
}
