// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :one
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, user_id, role, joined_at
`

type AddWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, slug, owner_id)
VALUES ($1, $2, $3)
RETURNING id, name, slug, logo_url, plan, owner_id, analyses_this_month, analyses_limit, api_requests_this_month, api_requests_limit, created_at, updated_at, deleted_at, brand_primary_color, brand_secondary_color, brand_font
`

type CreateWorkspaceParams struct {
	Name    string    `json:"name"`
	Slug    string    `json:"slug"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.Slug, arg.OwnerID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.Plan,
		&i.OwnerID,
		&i.AnalysesThisMonth,
		&i.AnalysesLimit,
		&i.ApiRequestsThisMonth,
		&i.ApiRequestsLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.BrandPrimaryColor,
		&i.BrandSecondaryColor,
		&i.BrandFont,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, slug, logo_url, plan, owner_id, analyses_this_month, analyses_limit, api_requests_this_month, api_requests_limit, created_at, updated_at, deleted_at, brand_primary_color, brand_secondary_color, brand_font FROM workspaces WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.Plan,
		&i.OwnerID,
		&i.AnalysesThisMonth,
		&i.AnalysesLimit,
		&i.ApiRequestsThisMonth,
		&i.ApiRequestsLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.BrandPrimaryColor,
		&i.BrandSecondaryColor,
		&i.BrandFont,
	)
	return i, err
}

const incrementWorkspaceAnalysesUsage = `-- name: IncrementWorkspaceAnalysesUsage :exec
UPDATE workspaces SET analyses_this_month = analyses_this_month + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementWorkspaceAnalysesUsage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementWorkspaceAnalysesUsage, id)
	return err
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT wm.id, wm.workspace_id, wm.user_id, wm.role, wm.joined_at, u.email, u.full_name FROM workspace_members wm
JOIN users u ON u.id = wm.user_id
WHERE wm.workspace_id = $1
ORDER BY wm.joined_at
`

type ListWorkspaceMembersRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	Email       string             `json:"email"`
	FullName    string             `json:"full_name"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Email,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.name, w.slug, w.logo_url, w.plan, w.owner_id, w.analyses_this_month, w.analyses_limit, w.api_requests_this_month, w.api_requests_limit, w.created_at, w.updated_at, w.deleted_at, w.brand_primary_color, w.brand_secondary_color, w.brand_font FROM workspaces w
JOIN workspace_members wm ON wm.workspace_id = w.id
WHERE wm.user_id = $1 AND w.deleted_at IS NULL
ORDER BY w.created_at DESC
`

func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LogoUrl,
			&i.Plan,
			&i.OwnerID,
			&i.AnalysesThisMonth,
			&i.AnalysesLimit,
			&i.ApiRequestsThisMonth,
			&i.ApiRequestsLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.BrandPrimaryColor,
			&i.BrandSecondaryColor,
			&i.BrandFont,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspaceBrand = `-- name: UpdateWorkspaceBrand :one
UPDATE workspaces
SET brand_primary_color = $2, brand_secondary_color = $3, brand_font = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, logo_url, plan, owner_id, analyses_this_month, analyses_limit, api_requests_this_month, api_requests_limit, created_at, updated_at, deleted_at, brand_primary_color, brand_secondary_color, brand_font
`

type UpdateWorkspaceBrandParams struct {
	ID                  uuid.UUID   `json:"id"`
	BrandPrimaryColor   pgtype.Text `json:"brand_primary_color"`
	BrandSecondaryColor pgtype.Text `json:"brand_secondary_color"`
	BrandFont           pgtype.Text `json:"brand_font"`
}

func (q *Queries) UpdateWorkspaceBrand(ctx context.Context, arg UpdateWorkspaceBrandParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceBrand,
		arg.ID,
		arg.BrandPrimaryColor,
		arg.BrandSecondaryColor,
		arg.BrandFont,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.Plan,
		&i.OwnerID,
		&i.AnalysesThisMonth,
		&i.AnalysesLimit,
		&i.ApiRequestsThisMonth,
		&i.ApiRequestsLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.BrandPrimaryColor,
		&i.BrandSecondaryColor,
		&i.BrandFont,
	)
	return i, err
}

const updateWorkspacePlan = `-- name: UpdateWorkspacePlan :one
UPDATE workspaces SET plan = $2, analyses_limit = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, logo_url, plan, owner_id, analyses_this_month, analyses_limit, api_requests_this_month, api_requests_limit, created_at, updated_at, deleted_at, brand_primary_color, brand_secondary_color, brand_font
`

type UpdateWorkspacePlanParams struct {
	ID            uuid.UUID `json:"id"`
	Plan          string    `json:"plan"`
	AnalysesLimit int32     `json:"analyses_limit"`
}

func (q *Queries) UpdateWorkspacePlan(ctx context.Context, arg UpdateWorkspacePlanParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspacePlan, arg.ID, arg.Plan, arg.AnalysesLimit)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.Plan,
		&i.OwnerID,
		&i.AnalysesThisMonth,
		&i.AnalysesLimit,
		&i.ApiRequestsThisMonth,
		&i.ApiRequestsLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.BrandPrimaryColor,
		&i.BrandSecondaryColor,
		&i.BrandFont,
	)
	return i, err
}
